name: BouncyBlocks
main: cupidonsauce173\BouncyBlocks\BouncyBlocks
version: 2.0.0
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8,3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: CupidonSauce173
description: Bounce on any block as if it were a trampoline.
load: POSTWORLD

commands:
    bounce:
        description: Enales or disables bouncing for the sender
        usage:  /bounce <true|false>
        permission: bouncyblocks.command

permissions:
    bouncyblocks:
        description: Gives player access to all BouncyBlocks permissions
        default: op
        children:
            bouncyblocks.command:
                description: Player can use the bounce command
                default: true
            bouncyblocks.bounce:
                description: Player can bounce on a BouncyBlock
                default: true
            bouncyblocks.takedamage:
                description: Player will take fall damage from bouncing on a BouncyBlock
                default: false
